[package]
name = "iscp"
version = "0.1.0"
authors = ["havoc <havoc.remake@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1"
if-addrs = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
