name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./onkyo
      run: cargo build --release
    - name: Run tests
      working-directory: ./onkyo
      run: cargo test --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: onkyo
          path: ./target/release/onkyo

      - name: List Artifacts
        run: ls ./target/release/onkyo
